import type { Metadata } from 'next'
// import { Inter } from "next/font/google";
import './globals.css'
import { Analytics } from '@vercel/analytics/next'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html className="h-full bg-zinc-900" lang="en">
            <body className="h-full">{children} 
                <Analytics/>
            </body>
        </html>
    )
}
